//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Logger_Capability
    {
        public long ID { get; set; }
        public string Username { get; set; }
        public string TacVu { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual SYS_Account SYS_Account { get; set; }
    }
}
