//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DataProvider.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemEntities : DbContext
    {
        public SystemEntities()
            : base("name=SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SYS_Account> SYS_Account { get; set; }
        public virtual DbSet<SYS_Capability> SYS_Capability { get; set; }
        public virtual DbSet<SYS_Capability_Account> SYS_Capability_Account { get; set; }
        public virtual DbSet<SYS_Capability_Role> SYS_Capability_Role { get; set; }
        public virtual DbSet<SYS_GroupLayer> SYS_GroupLayer { get; set; }
        public virtual DbSet<SYS_GroupRole> SYS_GroupRole { get; set; }
        public virtual DbSet<SYS_Layer> SYS_Layer { get; set; }
        public virtual DbSet<SYS_Layer_Account> SYS_Layer_Account { get; set; }
        public virtual DbSet<SYS_Layer_Role> SYS_Layer_Role { get; set; }
        public virtual DbSet<SYS_Logger_Capability> SYS_Logger_Capability { get; set; }
        public virtual DbSet<SYS_Logger_Layer> SYS_Logger_Layer { get; set; }
        public virtual DbSet<SYS_Role> SYS_Role { get; set; }
        public virtual DbSet<SYS_Version> SYS_Version { get; set; }
    }
}
